import { Geist, Geist_Mono ,Cairo} from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import ScrollProgressBar from "./components/ScrollProgressBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const cairo = Cairo({
  subsets: ["arabic"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${cairo.className} ${geistMono.variable} antialiased scroll-smooth `}
        cz-shortcut-listen="true"
      >
        <ScrollProgressBar />
        <Navbar />
        {children}
        <Footer />
     
      </body>
    </html>
  );
}
